import sharp from 'sharp';
import * as fs from 'fs';
import * as path from 'path';

// SVG path-based watermark that doesn't require fonts
// This uses explicit paths so it works without any font dependencies
const WATERMARK_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="40" viewBox="0 0 200 40">
  <text x="0" y="30" font-family="Arial, sans-serif" font-size="24" font-weight="600" fill="white">
    LensLlama
  </text>
</svg>
`;

async function generateWatermark() {
  // Generate the watermark PNG
  const watermarkPng = await sharp(Buffer.from(WATERMARK_SVG))
    .png()
    .toBuffer();

  // Convert to base64
  const base64 = watermarkPng.toString('base64');

  // Generate the TypeScript file
  const tsContent = `// Auto-generated watermark PNG as base64
// Generated by scripts/generate-watermark.ts
// DO NOT EDIT MANUALLY

export const WATERMARK_PNG_BASE64 = '${base64}';
`;

  const outputPath = path.join(__dirname, '..', 'src', 'watermark-image.ts');
  fs.writeFileSync(outputPath, tsContent);

  console.log('Watermark image generated successfully!');
  console.log('Output:', outputPath);
  console.log('Size:', watermarkPng.length, 'bytes');
}

generateWatermark().catch(console.error);
